### PR TITLE
update sample projects to latest sdk

### PR DESCRIPTION
**Pull request by ndurell**
# Description

Update Sample Projects to use the latest SDK.

# Check List

- [ ] Are you changing anything with the public API?
- [ ] Have you tested this change on real device?
- [ ] Are your changes backwards compatible with previous SDK Versions?
- [ ] Have you added unit test coverage for your changes?
- [ ] Have you verified that your changes are compatible with all the operating system version this SDK currently supports?

# Manual Test Plan

1.

# Supporting Materials

### CODE REVIEW

**Review by ajaysubra — APPROVED** [review]

**Review by evan-masseau — APPROVED** [review]
Looks fine for the 2.4 version increment. Probably should make a point in the future to merge this _before_ the release itself is published.

**Comment by ajaysubra** [comment]
> Looks fine for the 2.4 version increment. Probably should make a point in the future to merge this _before_ the release itself is published.

🤔 wouldn't you need the release to make the update?

> Looks fine for the 2.4 version increment. Probably should make a point in the future to merge this _before_ the release itself is published.

Hmm. Wouldn't you need the release in order to use it in the sample app?  Unless I'm misunderstanding something.

**Comment by ndurell** [comment]
> Looks fine for the 2.4 version increment. Probably should make a point in the future to merge this _before_ the release itself is published.

I'm not sure you can release before it published.

**Comment by evan-masseau** [comment]
OH duh.

**Pull request merged**
