### PR TITLE
Xcode 10.2 & Swift 5

### PR DESCRIPTION
**Pull request by floriankrueger**

### CODE REVIEW

**Comment by ndurell** [comment]
Thanks @floriankrueger! I think this just needs a small tweak to pass CI will update shortly.

**Comment by ndurell** [comment]
Hey @floriankrueger I just updated our .travis.yml do you mind giving this a rebase ?

**Comment by floriankrueger** [comment]
Hi @ndurell I rebased the branch but Travis still wasn't successful:

```$ pod lib lint
Could not find proper version of cocoapods (1.5.3) in any of the sources
Run `bundle install` to install missing gems.
The command "pod lib lint" exited with 7.```

Please ping me when you updated the config and I'll rebase again 👍

**Comment by ndurell** [comment]
Ok @floriankrueger sorry for the hassle. I've locked the dependencies in another PR and will let you know once that's merged. Not sure why this is happening to you as my other PRs built without issue.

**Comment by floriankrueger** [comment]
@ndurell no worries 🙂

**Comment by ndurell** [comment]
OK please give it one more try.

**Comment by floriankrueger** [comment]
Looks good now.

**Pull request merged**
